/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:10: RuntimeWarning: divide by zero encountered in divide
  t = (x - par[5])/par[6]
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:12: RuntimeWarning: invalid value encountered in scalar divide
  A = par[2]/par[0]
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:13: RuntimeWarning: invalid value encountered in scalar divide
  B = par[3]/par[1]
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:19: RuntimeWarning: invalid value encountered in scalar power
  f = math.exp(-0.5*par[0]**2)*(1/A*(A - par[0] -i))**(-par[2])
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:12: RuntimeWarning: divide by zero encountered in scalar divide
  A = par[2]/par[0]
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:19: RuntimeWarning: invalid value encountered in scalar multiply
  f = math.exp(-0.5*par[0]**2)*(1/A*(A - par[0] -i))**(-par[2])
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:13: RuntimeWarning: divide by zero encountered in scalar divide
  B = par[3]/par[1]
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:21: RuntimeWarning: invalid value encountered in scalar multiply
  f = math.exp(-0.5*par[1]**2)*(1/B*(B - par[1] +i))**(-par[3])
/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/model.py:21: RuntimeWarning: invalid value encountered in scalar power
  f = math.exp(-0.5*par[1]**2)*(1/B*(B - par[1] +i))**(-par[3])
Traceback (most recent call last):
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/test_SF.py", line 541, in <module>
    main()     
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/test_SF.py", line 526, in main
    plt_hfit = plottool.plot_data(hint_array[im,:,ct][g], hint_err_array[im,:,ct][g], x_noint, x_int[im,g], fit_params_int[:,g], fit_params_err, m.fval/dof, args.outDir, mp, label)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/python/plotting.py", line 59, in plot_data
    plt.savefig('%s/M%d/%s.png'%(plotdir,int(mass),hname))
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/pyplot.py", line 1229, in savefig
    fig.canvas.draw_idle()  # Need this if 'transparent=True', to reset colors.
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/backend_bases.py", line 1905, in draw_idle
    self.draw(*args, **kwargs)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 387, in draw
    self.figure.draw(self.renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/figure.py", line 3162, in draw
    mimage._draw_list_compositing_images(
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/axes/_base.py", line 3137, in draw
    mimage._draw_list_compositing_images(
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/axis.py", line 1427, in draw
    tick.draw(renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/axis.py", line 277, in draw
    artist.draw(renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/text.py", line 796, in draw
    textrenderer.draw_tex(gc, x, y, clean_line,
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 235, in draw_tex
    Z = texmanager.get_grey(s, size, self.dpi)
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/texmanager.py", line 337, in get_grey
    rgba = mpl.image.imread(os.path.join(cls._texcache, pngfile))
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/matplotlib/image.py", line 1544, in imread
    with img_open(fname) as image:
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/PIL/ImageFile.py", line 144, in __init__
    self._open()
  File "/afs/cern.ch/user/a/amkrishn/hggIntAnalysisScripts/myenv/lib64/python3.9/site-packages/PIL/PngImagePlugin.py", line 757, in _open
    raise SyntaxError(msg)
SyntaxError: not a PNG file
